server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ROOT
    url: jdbc:mysql://139.9.136.188:3306/yjc-im?useUnicode&characterEncode=utf-8
  data:
    redis:
      host: 139.9.136.188
      port: 6379
      password: ROOT
      database: 3

minio:
  endpoint: http://139.9.136.188:9001
  bucketName: yjc-im
  accessKey: root
  secretKey: Software.
