server:
  port: 8081
websocket:
  enable: true
  port: 8082
spring:
  data:
    redis:
      host: 139.9.136.188
      port: 6379
      password: ROOT
      database: 3
  rabbitmq:
    username: yjc
    password: ROOT
    virtual-host: /yjc
    host: 139.9.136.188
    port: 5672
    exchange: yjc-im
    private:
      queue: private27
      key: private27
    group:
      queue: group27
      key: group27
  main:
    allow-circular-references: true
